names = []
print('Enter 5 names:')
name1 = input()
name2 = input()
name3 = input()
name4 = input()
name5 = input()
names.append(name1)
names.append(name2)
names.append(name3)
names.append(name4)
names.append(name5)
print('The third name you entered is ' + str(names[2]))
