name = input("please input your name: ")
age = input("please input your age: ")
color = input("please input your favorite color: ")
food = input("please input your favorite food: ")

info = open('info.txt', 'w')
info.write(name+"\n")
info.write(age+"\n")
info.write(color+"\n")
info.write(food+"\n")
info.close()
