places = ['shanghai', 'beijing', 'guangzhou', 'chengdu', 'wuhan', 'nanjing']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort()
print(places)
