import time
import random

time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
time.sleep(3)
print(random.random())
